version: "3.9"
services:
  db:
    image: postgres:14.4-alpine
    container_name: 'docker-practice'
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: test
  
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"


